server:
  port: 8888

spring:
  profiles:
    active: ${ACTIVE_PROFILE}

google:
  client:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile email
    registered-redirect-uri: http://localhost:8888/dashboard
  resource:
    userInfoUri: https://www.googleapis.com/plus/v1/people/me

facebook:
  client:
    clientId: ${FACEBOOK_CLIENT_ID}
    clientSecret: ${FACEBOOK_CLIENT_SECRET}
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    registered-redirect-uri: http://localhost:8888/dashboard
  resource:
    userInfoUri: https://graph.facebook.com/me


